### ISSUE TITLE
Deal with a non Kiwix organisation

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#183]
Assuming someone wants to benefit from our CI/CD but already owns the app in his organisation:
* How could we upload a custom app to his organisation instead of ours? 
* What kind of things should be changed?

**Comment by benoit74** [comment]
If I understand this issue correctly, I think implementing this would be useful not only for cases where a client already owns the app (id), but also for cases where the client simply would like to publish the app under his own organization (instead of kiwix), typically for "marketing" purposes.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 For uploading the application on a non-kiwix organization we have some things from the organization(it is optional, it is only required when they want to publish their application with their own keystore file. Otherwise our current key will work for these apps) and we have to change our `cd` of custom apps.


First-time organizations have to publish their application on the play console manually(https://github.com/Triple-T/gradle-play-publisher?tab=readme-ov-file#initial-play-store-upload) (or they can give access of the play console to us and we can upload that for them), after that, it will be automatically published by our cd.

**What we require from the organization**
* keystore file. (optional)
* key alias. (optional)
* key password. (optional)
* keystore password. (optional)
* Service account `json` file. (**Required**) Full documentation here(https://github.com/Triple-T/gradle-play-publisher?tab=readme-ov-file#service-account) about how to create the JSON file and add the user to their playStore account for publishing the application. 


**What needs to change in the CD**
* We have a `Preparing signing material` job in our `CD` which fetches the `playstore.json`(service account JSON), keystore file from secrets of our Git Hub.
* For non-kiwix organizations we will put their `playstore.json` file in our secrets with a tag so that we can fetch this file in our CD based on the `TAG`. Here `TAG` is the folder name of the application(e.g. in this example `dwds`).
     **For example:** Currently, we are aiming this for the `dwds` application, so here we will put the JSON file in our secrets like this: `PLAYSTORE_JSON_dwds`.
    * **If they want to use their keystore file**: Then we will put their `keystore` file in our secrets with a tag like this `keystore_dwds`. Also, in this case, we have to put the `KEY_ALIAS_dwds`, `KEY_PASSWORD_dwds`, and `KEY_STORE_PASSWORD_dwds` in our secrets for creating the application in release mode.

**What we need to change in the custom apps**
* We need to change the `info.json` file to know whether it is another organization app or not so that we can fetch the secrets in our CD based on it.
* One more thing we have to add, is whether the organization using its own keystore file or not. So that we will get the secrets in the CD based on it.


@kelson42, @benoit74 This is my plan to implement this. If you have any suggestions in this let me know.

**Comment by MohitMaliFtechiz** [comment]
> What are the reason an organization might want us to use their keystore / key ? I mean, we are the ones publishing, we take the responsibility to sign the application with our material. Is this something too visible for end-users (I'm not speaking about devs / nerds which should probably not be considered)?

This is a suggestion for preparing our CD for that case, that's why I have marked this optional.

> document the procedure (typically how to create and configure the service account) in our own documentation (not the one of someone else which might disappear / give unrelated details we are not interesting into)

Thanks this is the documentation part, and we will include this in our readme file.

> find a way to test what will be developed, otherwise there is just too much chances this won't work when we will need it (or agree to not start work on this issue until we have a real use case which can be used for testing, but this does not look very professional IMO, especially since we might have to test this on a regular basis - once a year? - to not discover something has changed on google side when we will need this feature - obviously urgently because "shit happens" 🤣)

Now, we will test this system with the dwds application. Since dwds wants to release an application in his organization.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the detailed proposal. What is clear to me a this stage is that I see no reason to have a custom keystore. Therefore we stay with only the JSON. Regarding the documentation please explain only the Kiwix specific part: how to create the JSON and how to put it in the SECRET is "not our business".
