### ISSUE TITLE
Create Kiwix-kids app with offline stuffs for kids.

### ISSUE THREAD

**Issue by johnn-oss** [kiwix/kiwix-android-custom#59]
- Let the app:

- Filter adult contents 

- contain fun activities & exercises from Popular kids website

- Contain free resources for kids from Wikipedia just like Kiwix.
   & lots of other interesting stuffs!

**Comment by Popolechien** [comment]
@johnn-oss That's a little outside of our skillset and resources - what we do is repackage existing (freely licensed) content so that it works offline, Content filtering in and of itself is an entirely different animal.
If you know of any particular website that fits this free-license requirement, feel free to post a more specific request, but for the time being I'll have to close the issue.

**Comment by macgills** [comment]
Vikidia's tagline is "For 8-13yr old children" but that content is very small for deploying a custom app.

**Comment by johnn-oss** [comment]
> @johnn-oss That's a little outside of our skillset and resources - what we do is repackage existing (freely licensed) content so that it works offline, Content filtering in and of itself is an entirely different animal.
> If you know of any particular website that fits this free-license requirement, feel free to post a more specific request, but for the time being I'll have to close the issue.

OK thanks @Popolechien , but I don't know much about " free-license" websites. I didn't get what I want from Google. can you hint me more. Thanks

**Comment by kelson42** [comment]
@johnn-oss I recomment to read https://en.wikipedia.org/wiki/Free_content and https://en.wikipedia.org/wiki/Free-culture_movement

**Comment by johnn-oss** [comment]
> @johnn-oss I recomment to read https://en.wikipedia.org/wiki/Free_content and https://en.wikipedia.org/wiki/Free-culture_movement

Thanks @kelson42 it was helpful
